id: IB0603AEF
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-368f
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 11:58:55.695278+00:00
last_modified: 2023-09-28 11:58:55.695283+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG03845
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG03845
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་རྒྱ་ཆེར་འགྲེལ་པ་བསྟན་པ་བསྲུང་བ།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.6077335189714308
  ocr_word_median_confidence_index: 0.5825716000000001
bases:
  I00KG03874:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03874
      total_pages: 202
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG03874.txt
    statistics:
      ocr_word_median_confidence_index: 0.5825716000000001
      ocr_word_mean_confidence_index: 0.6077335189714308
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
